# Generated by Django 5.0 on 2025-11-25 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='カテゴリ名称')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, verbose_name='地区名称')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spot_name', models.CharField(max_length=100, verbose_name='観光地名称')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('explanation', models.TextField(max_length=2000, verbose_name='説明')),
                ('business_hours', models.CharField(max_length=100, verbose_name='営業時間')),
                ('regular_holiday', models.CharField(max_length=100, verbose_name='定休日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp_admin.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp_admin.district')),
            ],
        ),
    ]
