# Generated by Django 5.2.8 on 2026-01-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0002_events_delete_event_and_more'),
        ('spotapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osirase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maintenance', 'メンテナンス'), ('cancel', '中止・延期'), ('other', 'その他')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='district',
        ),
        migrations.RemoveField(
            model_name='events',
            name='spot_id',
        ),
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='spotapp.events'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot_photos', to='spotapp.spot'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
