# Generated by Django 5.0 on 2025-11-25 02:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
