# Generated by Django 5.2.8 on 2026-01-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0002_osirase'),
        ('spotapp_admin', '0002_osirase_remove_spot_category_remove_spot_district_and_more'),
    ]

    operations = [
    ]
