# Generated by Django 5.2.8 on 2026-01-15 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0002_remove_osirase_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, verbose_name='地区名称')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='osirase',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
