# Generated by Django 5.0 on 2025-11-25 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, verbose_name='イベント名称')),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('venue', models.CharField(max_length=255, verbose_name='会場')),
                ('details', models.TextField(max_length=2000, verbose_name='詳細情報')),
                ('organizer', models.CharField(max_length=255, verbose_name='主催者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('spot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotapp_admin.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/', verbose_name='写真')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spotapp_admin.events')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spotapp_admin.spot')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
