# Generated by Django 5.2.8 on 2026-01-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0003_district_alter_osirase_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
