# Generated by Django 5.0.4 on 2026-01-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0005_osirase_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='spotapp_admin/', verbose_name='写真'),
        ),
    ]
