# Generated by Django 5.0 on 2025-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='spotapp_admin/photos/', verbose_name='写真'),
        ),
    ]
