# Generated by Django 5.0 on 2025-11-26 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
