# Generated by Django 5.0.4 on 2026-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
