# Generated by Django 5.0.4 on 2026-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0002_spot_latitude_spot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='regular_holiday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='定休日'),
        ),
    ]
