# Generated by Django 5.0.4 on 2026-01-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0005_events_address_events_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
        migrations.AddField(
            model_name='events',
            name='event_end',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_start',
            field=models.DateField(blank=True, null=True, verbose_name='開催日'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='開催時間'),
        ),
    ]
