# Generated by Django 5.0.4 on 2026-01-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp_admin', '0004_delete_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='osirase',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_osirase', to='spotapp_admin.staff'),
        ),
    ]
