<<<<<<< HEAD
# Generated by Django 5.0 on 2025-11-28 04:58
=======
# Generated by Django 5.0.4 on 2026-01-09 02:07
>>>>>>> ede5ab6a0a2d6435e2d95a0472d64358ecc18d9b

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='カテゴリ名称')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, verbose_name='地区名称')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, verbose_name='イベント名称')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('location', models.CharField(max_length=200, verbose_name='開催場所')),
                ('official_url', models.URLField(blank=True, null=True, verbose_name='公式サイトURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='イベント説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profile_icons/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spot_name', models.CharField(max_length=100, verbose_name='観光地名称')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('explanation', models.TextField(max_length=2000, verbose_name='説明')),
                ('business_hours', models.CharField(max_length=100, verbose_name='営業時間')),
                ('regular_holiday', models.CharField(max_length=100, verbose_name='定休日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '★1'), (2, '★2'), (3, '★3'), (4, '★4'), (5, '★5')])),
                ('comment', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.user')),
            ],
        ),
    ]
