# Generated by Django 5.2.8 on 2026-01-08 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=255, verbose_name='イベント名称')),
                ('event_date', models.DateField(verbose_name='開催日')),
                ('venue', models.CharField(max_length=255, verbose_name='会場')),
                ('details', models.TextField(max_length=2000, verbose_name='詳細情報')),
                ('organizer', models.CharField(max_length=255, verbose_name='主催者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('spot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotapp.spot')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spotapp.spot'),
        ),
    ]
