# Generated by Django 5.2.8 on 2025-11-28 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, verbose_name='イベント名称')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('location', models.CharField(max_length=200, verbose_name='開催場所')),
                ('official_url', models.URLField(blank=True, null=True, verbose_name='公式サイトURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='イベント説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
    ]
