# Generated by Django 5.2.8 on 2026-01-16 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0003_alter_spot_regular_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp.category'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotapp.district'),
        ),
    ]
