# Generated by Django 5.0.4 on 2026-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0004_alter_spot_category_alter_spot_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.CharField(default='', max_length=255, verbose_name='開催時間'),
            preserve_default=False,
        ),
    ]
